# Generated by Django 5.0.3 on 2024-06-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NAVR_RecentNews',
            fields=[
                ('news_unique_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('news_page_id', models.CharField(max_length=15)),
                ('news_title', models.CharField(max_length=100)),
                ('news_datetime', models.DateTimeField(verbose_name='news published datetime')),
                ('news_press_id', models.CharField(max_length=5)),
                ('news_press_name', models.CharField(max_length=100)),
                ('news_lede', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'NEWS_NAVER_RECENTNEWS',
                'db_table_comment': '뉴스 네이버 최신뉴스',
            },
        ),
        migrations.CreateModel(
            name='NMWK_RecentChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('edit_datetime', models.DateTimeField(verbose_name='edit datetime')),
                ('edit_editer', models.CharField(max_length=200)),
                ('edit_comment', models.CharField(max_length=1000, null=True)),
                ('edit_len_byte', models.IntegerField()),
            ],
            options={
                'db_table': 'NAMUWIKI_RECENTCHANGES',
                'db_table_comment': '나무위키 최근변경',
            },
        ),
        migrations.CreateModel(
            name='NMWK_TrendSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_num', models.IntegerField()),
                ('search_word', models.CharField(max_length=200)),
                ('provide_datetime', models.DateTimeField(verbose_name='When provided')),
            ],
            options={
                'db_table': 'NAMUWIKI_TRENDSEARCH',
                'db_table_comment': '나무위키 인기검색어',
            },
        ),
        migrations.CreateModel(
            name='ZUM_TrendSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_num', models.IntegerField()),
                ('search_word', models.CharField(max_length=200)),
                ('rank_updown', models.CharField(max_length=20)),
                ('provide_datetime', models.DateTimeField(verbose_name='When provided')),
            ],
            options={
                'db_table': 'ZUM_TRENDSEARCH',
                'db_table_comment': '줌 인기검색어',
            },
        ),
    ]
