# Generated by Django 5.0.3 on 2024-07-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collected_data', '0002_nate_trendsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLTDATA_MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt_channel_idx', models.IntegerField()),
                ('clt_channel_eng', models.CharField(max_length=100)),
                ('clt_channel_kor', models.CharField(max_length=100)),
                ('clt_channel_initial', models.CharField(max_length=20)),
                ('clt_datetime_recent_collected_data', models.DateTimeField(verbose_name='Lasted data update datetime')),
            ],
            options={
                'db_table': 'CLTDATA_MAININFO',
                'db_table_comment': '수집채널 메인 정보',
            },
        ),
    ]
