# Generated by Django 5.0.3 on 2024-07-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collected_data', '0003_cltdata_maininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cltdata_maininfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='cltdata_maininfo',
            name='clt_channel_idx',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
